# Generated by Django 2.0.2 on 2018-03-07 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_snapfile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapfile',
            name='number_scripts',
            field=models.IntegerField(default=0, verbose_name='number_scripts'),
        ),
        migrations.AddField(
            model_name='snapfile',
            name='number_sprites',
            field=models.IntegerField(default=0, verbose_name='number_sprites'),
        ),
        migrations.AlterField(
            model_name='snapfile',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['xml', 'XML'])], verbose_name='File'),
        ),
    ]
