# Generated by Django 2.0.1 on 2018-07-17 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180307_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='password',
            field=models.CharField(default='pw', max_length=200, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='project',
            name='pin',
            field=models.CharField(default='000000', max_length=6, unique=True, verbose_name='PIN'),
        ),
        migrations.AlterField(
            model_name='snapfile',
            name='file',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['xml', 'XML'])], verbose_name='File'),
        ),
    ]
