# Generated by Django 2.0.1 on 2018-07-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180717_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pin',
            field=models.CharField(max_length=6, unique=True, verbose_name='PIN'),
        ),
    ]
