# Generated by Django 2.0.1 on 2018-07-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180717_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
    ]
