# Generated by Django 2.0.2 on 2018-07-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180718_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project'),
        ),
    ]
