# Generated by Django 2.1 on 2019-05-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_project_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapfile',
            name='color',
            field=models.CharField(default='#386561', max_length=7, verbose_name='color'),
        ),
    ]
