# Generated by Django 3.0.7 on 2023-09-27 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_snapfile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapfile',
            name='color',
            field=models.CharField(default='#076AAB', max_length=7, verbose_name='color'),
        ),
        migrations.CreateModel(
            name='MergeConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leftFile', to='home.SnapFile')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rightFile', to='home.SnapFile')),
            ],
        ),
        migrations.CreateModel(
            name='Hunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leftHunk', to='home.SnapFile')),
                ('mergeConflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MergeConflict')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rightHunk', to='home.SnapFile')),
            ],
        ),
    ]
