# Generated by Django 3.0.7 on 2023-09-27 01:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20230927_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergeconflict',
            name='project',
            field=models.ForeignKey(default='d7af4edb96b54e98a4625e8d288bf528', on_delete=django.db.models.deletion.CASCADE, to='home.Project'),
        ),
        migrations.CreateModel(
            name='ConflictFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('number_scripts', models.IntegerField(default=0, verbose_name='number_scripts')),
                ('number_sprites', models.IntegerField(default=0, verbose_name='number_sprites')),
                ('color', models.CharField(default='#076AAB', max_length=7, verbose_name='color')),
                ('file', models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['xml', 'XML', 'txt', 'TXT', 'base64', 'BASE64'])], verbose_name='File')),
                ('ancestors', models.ManyToManyField(to='home.ConflictFile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
            options={
                'verbose_name': 'ConflictFile',
                'verbose_name_plural': 'ConflictFiles',
            },
        ),
        migrations.AlterField(
            model_name='hunk',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leftHunk', to='home.ConflictFile'),
        ),
        migrations.AlterField(
            model_name='hunk',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rightHunk', to='home.ConflictFile'),
        ),
    ]
