# Generated by Django 3.0.7 on 2023-09-27 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20230927_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunk',
            name='choice',
            field=models.CharField(max_length=30, null=True, verbose_name='choice'),
        ),
        migrations.AlterField(
            model_name='mergeconflict',
            name='project',
            field=models.ForeignKey(default='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', on_delete=django.db.models.deletion.CASCADE, to='home.Project'),
        ),
    ]
