# Generated by Django 5.0 on 2023-12-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20230927_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapfile',
            name='xPosition',
            field=models.FloatField(null=True, verbose_name='xPosition'),
        ),
        migrations.AddField(
            model_name='snapfile',
            name='yPosition',
            field=models.FloatField(null=True, verbose_name='yPosition'),
        ),
        migrations.AlterField(
            model_name='conflictfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hunk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mergeconflict',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='snapfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
