# Generated by Django 5.0 on 2024-01-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_snapfile_xposition_snapfile_yposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapfile',
            name='xPosition',
            field=models.FloatField(default=0, verbose_name='xPosition'),
        ),
        migrations.AlterField(
            model_name='snapfile',
            name='yPosition',
            field=models.FloatField(default=0, verbose_name='yPosition'),
        ),
    ]
