# Generated by Django 5.0 on 2024-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_snapfile_xposition_alter_snapfile_yposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapfile',
            name='collapsed',
            field=models.BooleanField(default=False, verbose_name='collapsed'),
        ),
        migrations.AddField(
            model_name='snapfile',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AddField(
            model_name='snapfile',
            name='type',
            field=models.CharField(default='default', max_length=30, null=True, verbose_name='type'),
        ),
    ]
