# Generated by Django 5.0 on 2024-01-27 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_snapfile_collapsed_snapfile_hidden_snapfile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='conflict_color',
            field=models.CharField(default='#d0021b', max_length=7, verbose_name='conflict_color'),
        ),
        migrations.AddField(
            model_name='project',
            name='default_color',
            field=models.CharField(default='#076AAB', max_length=7, verbose_name='node_color'),
        ),
        migrations.AddField(
            model_name='project',
            name='favor_color',
            field=models.CharField(default='#417505', max_length=7, verbose_name='favor_color'),
        ),
        migrations.AlterField(
            model_name='snapfile',
            name='file',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['xml', 'XML', 'conflict'])], verbose_name='File'),
        ),
    ]
