# Generated by Django 5.0 on 2024-01-28 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_project_conflict_color_project_default_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergeconflict',
            name='connected_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='connected_file', to='home.snapfile'),
        ),
    ]
