# Generated by Django 5.0 on 2024-02-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_mergeconflict_connected_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=255)),
                ('type', models.CharField(default='default', max_length=30, null=True)),
            ],
        ),
    ]
