# Generated by Django 5.0 on 2024-02-04 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_settings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunk',
            name='mergeConflict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.mergeconflict'),
        ),
        migrations.AlterField(
            model_name='mergeconflict',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leftFile', to='home.snapfile'),
        ),
        migrations.AlterField(
            model_name='mergeconflict',
            name='project',
            field=models.ForeignKey(default='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', on_delete=django.db.models.deletion.DO_NOTHING, to='home.project'),
        ),
        migrations.AlterField(
            model_name='mergeconflict',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rightFile', to='home.snapfile'),
        ),
    ]
