# Generated by Django 5.0 on 2024-02-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_conflictfile_cx_conflictfile_cy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictfile',
            name='cx',
            field=models.FloatField(null=True, verbose_name='cx'),
        ),
        migrations.AlterField(
            model_name='conflictfile',
            name='cy',
            field=models.FloatField(null=True, verbose_name='cy'),
        ),
    ]
