# Generated by Django 5.0 on 2024-02-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_conflictfile_cx_alter_conflictfile_cy'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictfile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
    ]
