# Generated by Django 5.0 on 2024-03-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='password',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Password'),
        ),
    ]
