# Generated by Django 5.0 on 2024-04-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_snapfile_collapsed_under'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictfile',
            name='ancestors',
            field=models.ManyToManyField(related_name='children', to='home.conflictfile'),
        ),
        migrations.AlterField(
            model_name='snapfile',
            name='ancestors',
            field=models.ManyToManyField(related_name='children', to='home.snapfile'),
        ),
    ]
