# Generated by Django 5.0 on 2024-04-06 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_conflictfile_ancestors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictfile',
            name='file',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['xml', 'XML', 'txt', 'TXT', 'base64', 'BASE64', 'atxt', 'ATXT'])], verbose_name='File'),
        ),
    ]
