# Generated by Django 5.0 on 2024-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_conflictfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunk',
            name='allowBoth',
            field=models.BooleanField(default=False),
        ),
    ]
