# Generated by Django 5.1.4 on 2024-12-09 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_hunk_allowboth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kanban_board',
            field=models.TextField(default='{"columns":[\n            {"id":1,"title":"KanbanBoard.todo","cards":[]},\n            {"id":2,"title":"KanbanBoard.wip","cards":[]},\n            {"id":3,"title":"KanbanBoard.done","cards":[]}\n        ]}', verbose_name='kanban_board'),
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='schoolclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.schoolclass'),
        ),
    ]
