# SMERGE Access Server...
# Version: 1.0
# Use the official Nginx image as a base
FROM nginx:latest

# Install necessary packages for your Python and Node.js applications
RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
RUN apt-get install -y \
    python3 \
    python3-pip \
    libffi-dev \
    libssl-dev \
    libxml2-dev \
    libxslt-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zlib1g-dev \
    net-tools \
    nodejs \
    npm

# Set up a working directory for your application
WORKDIR /var/www/snapmerge

# Copy your application files into the container
COPY ./Access_Portal /var/www/snapmerge/Access_Portal
COPY ./react_extension/ext_nginx.conf /etc/nginx/conf.d/default.conf
COPY ./entrypoint.sh /var/www/snapmerge/

# Install Python dependencies for Web_Api
WORKDIR /var/www/snapmerge/Access_Portal/Web_Api
COPY ./Access_Portal/Web_Api/requirements.txt .
RUN pip install -r requirements.txt

# Install Node.js dependencies for access_portal
WORKDIR /var/www/snapmerge/Access_Portal/access_portal
RUN npm install

# Expose port 8000 for your Python application
EXPOSE 8000

# Start Nginx and your Python application
CMD ["/var/www/snapmerge/entrypoint.sh"]




# Project Files and Settings
RUN mkdir -p /var/www/snapmerge
WORKDIR /var/www/snapmerge
COPY . .

RUN pip install -r requirements.txt

RUN npm install
# Server
EXPOSE 8000
STOPSIGNAL SIGINT
RUN chmod +x ./entrypoint.sh
RUN ./entrypoint.sh
ENTRYPOINT ["python", "snapmerge/manage.py"]
CMD ["runserver", "0.0.0.0:8000", "--settings=config.settings_docker"]